import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex ${inter.className}`}>
        <Sidebar />
        <div className="min-h-[100dvh] bg-gray-100 w-full px-8">
          <main className="flex flex-col max-w-7xl w-full mx-auto gap-8 pt-8 pb-12">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
