import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: HACER BIEN EL MANEJO DEL DARKMODE PORQUE PONER dark: NO ES SOSTENIBLE
// TODO: TRATAR DE ESTANDARIZAR TODO ASI ES MAS FACIL HACER MAS COSAS CON EL MISMO CODIGO

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`md:flex md:h-[100dvh] ${inter.className}`}>
        <Sidebar />
        <div className="min-h-[100dvh] bg-gray-100 dark:bg-black w-full px-4 md:px-8 overflow-y-auto">
          <main className="flex flex-col max-w-7xl w-full mx-auto gap-8 pt-8 pb-12">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
